try{
    let a=0
    console.log(progrma)
    console.log("Program ran successfull")
}
catch(err){
    console.log("This is an error")
    console.log(p)
}
finally{
    console.log("This will run in all case") //finally will always run no matter what condition is
     
}